name: flutter_safe_phone_direct_caller
description: Simple flutter plugin to call a number directly, without going to phone dialer, from app. A fork of gh repo clone flutter_safe_phone_direct_caller
version: 2.1.1
homepage: https://github.com/mcfriend99
repository: https://github.com/mcfriend99/flutter-safe-phone-direct-caller

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_lints: 1.0.4

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.mcfriend99.fluttersafephonedirectcaller
        pluginClass: FlutterSafePhoneDirectCallerPlugin
      ios:
        pluginClass: FlutterSafePhoneDirectCallerPlugin
